// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Bismarck Game Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Смена пароля",
                "parameters": [
                    {
                        "description": "Данные для смены пароля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean"
                                },
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "units": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        },
                                        "task_forces": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        },
                                        "enemy_contacts": {
                                            "type": "array",
                                            "description": "Aggregated enemy contacts visible to the requesting player",
                                            "items": {
                                                "$ref": "#/definitions/bismarck-game_backend_internal_game_models.EnemyContact"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Выход из системы",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Получение профиля пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Обновление профиля пользователя",
                "parameters": [
                    {
                        "description": "Данные для обновления профиля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Валидация токена",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/emergency-fuel/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emergency Fuel"
                ],
                "summary": "Проверка и активация аварийного топлива",
                "parameters": [
                    {
                        "description": "Данные для проверки аварийного топлива",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CheckEmergencyFuelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CheckEmergencyFuelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/emergency-fuel/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emergency Fuel"
                ],
                "summary": "Получение статуса аварийного топлива",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID юнита",
                        "name": "unit_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.CheckEmergencyFuelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Получение списка игр",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество элементов на странице",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Статус игры",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поиск по названию",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Создание новой игры",
                "parameters": [
                    {
                        "description": "Данные для создания игры",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.CreateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{gameId}/units/{unitId}/available-moves": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movement"
                ],
                "summary": "Получение доступных ходов для юнита",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID юнита",
                        "name": "unitId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.AvailableMovesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{gameId}/units/{unitId}/move": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movement"
                ],
                "summary": "Выполнение движения юнита",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID юнита",
                        "name": "unitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для движения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.MovementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.MovementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{gameId}/units/{unitId}/movement-history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movement"
                ],
                "summary": "Получение истории движения юнита",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID юнита",
                        "name": "unitId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Лимит записей",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bismarck-game_backend_internal_game_models.MovementHistory"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{gameId}/visibility/units": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visibility"
                ],
                "summary": "Получение видимых юнитов для игрока",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID игрока",
                        "name": "player_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.VisibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{gameId}/visibility/update": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visibility"
                ],
                "summary": "Обновление видимости юнита",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления видимости",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.VisibilityUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Получение информации об игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Удаление игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{id}/join": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Присоединение к игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для присоединения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.JoinGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{id}/surrender": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Сдача в игре",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{id}/units": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Получение юнитов игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/games/{id}/victory-points": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Получение очков победы для игры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Получение информации о всех фазах",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/complete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Завершение текущей фазы",
                "parameters": [
                    {
                        "description": "Данные для завершения фазы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Получение информации о фазе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название фазы",
                        "name": "phase",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/next": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Переход к следующей фазе",
                "parameters": [
                    {
                        "description": "Данные для перехода к следующей фазе",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/records": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Получение записей фаз",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID игры",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер хода",
                        "name": "turn",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/start": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Запуск новой фазы",
                "parameters": [
                    {
                        "description": "Данные для запуска фазы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/phases/turn/start": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Phases"
                ],
                "summary": "Запуск нового хода",
                "parameters": [
                    {
                        "description": "Данные для запуска хода",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/refuel/all": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Refuel"
                ],
                "summary": "Заправка всех кораблей в игре",
                "parameters": [
                    {
                        "description": "Данные для заправки",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.RefuelAllRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/all": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение всех кораблей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/config/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение конфигурации корабля",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID корабля",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/create-unit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Создание юнита из конфигурации",
                "parameters": [
                    {
                        "description": "Данные для создания юнита",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Поиск кораблей по критериям",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Сторона",
                        "name": "side",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Тип корабля",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Минимальное топливо",
                        "name": "min_fuel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Максимальное топливо",
                        "name": "max_fuel",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Минимальное уклонение",
                        "name": "min_evasion",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Максимальное уклонение",
                        "name": "max_evasion",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/side/{side}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение доступных кораблей для стороны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Сторона (german/allied)",
                        "name": "side",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/stats": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение статистики конфигурации",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/type/{type}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение кораблей по типу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Тип корабля",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ships/types": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ships"
                ],
                "summary": "Получение типов кораблей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bismarck-game_backend_internal_game_models.AvailableMovesResponse": {
            "type": "object",
            "properties": {
                "available_hexes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "current_hex": {
                    "type": "string"
                },
                "fuel_costs": {
                    "description": "Гекс -\u003e стоимость топлива",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "max_distance": {
                    "type": "integer"
                },
                "unit_id": {
                    "type": "string"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "bismarck-game_backend_internal_game_models.CreateGameRequest": {
            "type": "object",
            "required": [
                "name",
                "side"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "password": {
                    "type": "string"
                },
                "settings": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.GameSettings"
                },
                "side": {
                    "enum": [
                        "german",
                        "allied"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.PlayerSide"
                        }
                    ]
                }
            }
        },
        "bismarck-game_backend_internal_game_models.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "bismarck-game_backend_internal_game_models.EnemyContact": {
            "type": "object",
            "properties": {
                "class_summary": {
                    "type": "string",
                    "description": "Сводка по обнаруженным классам кораблей (например, BB×2, CV×1)"
                },
                "detection_level": {
                    "enum": [
                        "sighted",
                        "shadowed"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.DetectionLevel"
                        }
                    ]
                },
                "enemy_nationality": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.PlayerSide"
                        }
                    ]
                },
                "hex_id": {
                    "type": "string",
                    "description": "Координата гекса, где обнаружен контакт"
                },
                "last_seen_at": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Время последнего подтвержденного наблюдения"
                },
                "phase": {
                    "type": "string",
                    "description": "Фаза, в которой была зафиксирована информация"
                },
                "searching_side": {
                    "description": "Сторона, выполнившая поиск",
                    "allOf": [
                        {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.PlayerSide"
                        }
                    ]
                },
                "ship_count": {
                    "type": "integer",
                    "description": "Количество обнаруженных кораблей"
                },
                "task_force": {
                    "type": "string",
                    "description": "Название обнаруженной Task Force или 'нет'"
                },
                "task_force_list": {
                    "description": "Подробный список обнаруженных TF",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "turn": {
                    "type": "integer",
                    "description": "Номер хода"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.GameSettings": {
            "type": "object",
            "properties": {
                "allow_spectators": {
                    "type": "boolean"
                },
                "auto_save": {
                    "type": "boolean"
                },
                "difficulty": {
                    "type": "string"
                },
                "enable_crew_exhaustion": {
                    "type": "boolean"
                },
                "max_turn_time": {
                    "description": "в минутах",
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "private_lobby": {
                    "type": "boolean"
                },
                "time_limit_minutes": {
                    "type": "integer"
                },
                "use_optional_units": {
                    "type": "boolean"
                },
                "victory_conditions": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.VictoryConfig"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.JoinGameRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "side": {
                    "description": "Желаемая сторона (german или allied)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/bismarck-game_backend_internal_game_models.PlayerSide"
                        }
                    ]
                }
            }
        },
        "bismarck-game_backend_internal_game_models.LastKnownPosition": {
            "type": "object",
            "properties": {
                "last_seen_at": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "string"
                },
                "unit_type": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.UnitType"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.Movement": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "from_hex": {
                    "type": "string"
                },
                "fuel_cost": {
                    "type": "integer"
                },
                "game_id": {
                    "type": "string"
                },
                "hexes_moved": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "movement_type": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.MovementType"
                },
                "path": {
                    "description": "Путь движения (массив гексов)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "phase": {
                    "type": "string"
                },
                "to_hex": {
                    "type": "string"
                },
                "turn": {
                    "type": "integer"
                },
                "unit_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.MovementHistory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "game_id": {
                    "type": "string"
                },
                "hexes_moved": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "turn": {
                    "type": "integer"
                },
                "unit_id": {
                    "type": "string"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.MovementRequest": {
            "type": "object",
            "required": [
                "to_hex",
                "unit_id"
            ],
            "properties": {
                "path": {
                    "description": "Опциональный путь, если не указан - будет рассчитан",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "to_hex": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "string"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.MovementResponse": {
            "type": "object",
            "properties": {
                "fuel_cost": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "movement": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.Movement"
                },
                "new_position": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.MovementType": {
            "type": "string",
            "enum": [
                "normal",
                "pursued",
                "emergency"
            ],
            "x-enum-comments": {
                "MovementTypeEmergency": "Аварийное движение (при нехватке топлива)",
                "MovementTypeNormal": "Обычное движение",
                "MovementTypePursued": "Движение преследуемого юнита"
            },
            "x-enum-descriptions": [
                "Обычное движение",
                "Движение преследуемого юнита",
                "Аварийное движение (при нехватке топлива)"
            ],
            "x-enum-varnames": [
                "MovementTypeNormal",
                "MovementTypePursued",
                "MovementTypeEmergency"
            ]
        },
        "bismarck-game_backend_internal_game_models.PlayerSide": {
            "type": "string",
            "enum": [
                "german",
                "allied"
            ],
            "x-enum-varnames": [
                "PlayerSideGerman",
                "PlayerSideAllied"
            ]
        },
        "bismarck-game_backend_internal_game_models.UnitType": {
            "type": "string",
            "enum": [
                "BB",
                "BC",
                "CV",
                "CA",
                "CL",
                "DD",
                "CG",
                "TK",
                "B",
                "R"
            ],
            "x-enum-varnames": [
                "UnitTypeBattleship",
                "UnitTypeBattlecruiser",
                "UnitTypeAircraftCarrier",
                "UnitTypeHeavyCruiser",
                "UnitTypeLightCruiser",
                "UnitTypeDestroyer",
                "UnitTypeCoastGuard",
                "UnitTypeTanker",
                "UnitTypeCombatAircraft",
                "UnitTypeReconAircraft"
            ]
        },
        "bismarck-game_backend_internal_game_models.UnitVisibility": {
            "type": "string",
            "enum": [
                "unknown",
                "sighted",
                "shadowed"
            ],
            "x-enum-comments": {
                "VisibilityShadowed": "Юнит преследуется (маркер \"Преследуется\")",
                "VisibilitySighted": "Юнит обнаружен (маркер \"Обнаружено\")",
                "VisibilityUnknown": "Юнит не обнаружен"
            },
            "x-enum-descriptions": [
                "Юнит не обнаружен",
                "Юнит обнаружен (маркер \"Обнаружено\")",
                "Юнит преследуется (маркер \"Преследуется\")"
            ],
            "x-enum-varnames": [
                "VisibilityUnknown",
                "VisibilitySighted",
                "VisibilityShadowed"
            ]
        },
        "bismarck-game_backend_internal_game_models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "bismarck-game_backend_internal_game_models.VictoryConfig": {
            "type": "object",
            "properties": {
                "bismarck_end_game_vp": {
                    "type": "integer"
                },
                "bismarck_france_vp": {
                    "type": "integer"
                },
                "bismarck_no_fuel_vp": {
                    "type": "integer"
                },
                "bismarck_norway_vp": {
                    "type": "integer"
                },
                "bismarck_sunk_vp": {
                    "type": "integer"
                },
                "convoy_vp": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ship_vp_values": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "bismarck-game_backend_internal_game_models.VisibilityResponse": {
            "type": "object",
            "properties": {
                "last_known_positions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bismarck-game_backend_internal_game_models.LastKnownPosition"
                    }
                },
                "phase": {
                    "type": "string"
                },
                "turn": {
                    "type": "integer"
                },
                "visible_units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bismarck-game_backend_internal_game_models.VisibleUnit"
                    }
                }
            }
        },
        "bismarck-game_backend_internal_game_models.VisibilityUpdate": {
            "type": "object",
            "required": [
                "unit_id",
                "visibility"
            ],
            "properties": {
                "hex": {
                    "description": "Позиция, где был обнаружен юнит",
                    "type": "string"
                },
                "unit_id": {
                    "type": "string"
                },
                "visibility": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.UnitVisibility"
                }
            }
        },
        "bismarck-game_backend_internal_game_models.VisibleUnit": {
            "type": "object",
            "properties": {
                "last_seen_at": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "string"
                },
                "unit_type": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.UnitType"
                },
                "visibility": {
                    "$ref": "#/definitions/bismarck-game_backend_internal_game_models.UnitVisibility"
                }
            }
        },
        "internal_api_handlers.CheckEmergencyFuelRequest": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "string"
                }
            }
        },
        "internal_api_handlers.CheckEmergencyFuelResponse": {
            "type": "object",
            "properties": {
                "current_fuel": {
                    "type": "integer"
                },
                "emergency_turn": {
                    "type": "integer"
                },
                "is_emergency_fuel": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_api_handlers.RefuelAllRequest": {
            "type": "object",
            "properties": {
                "fuel_amount": {
                    "type": "integer"
                },
                "game_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "JWT токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Bismarck Game API",
	Description:      "API для игры Bismarck Chase - пошаговой стратегической игры о морских сражениях",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
