version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bismarck-postgres
    environment:
      POSTGRES_DB: bismarck_game
      POSTGRES_USER: bismarck_user
      POSTGRES_PASSWORD: bismarck_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bismarck_user -d bismarck_game"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: bismarck-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

  
